{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tatara-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tatara-operator.labels" . | nindent 4 }}
type: Opaque
data:
  OPERATOR_OIDC_CLIENT_SECRET: {{ .Values.operatorOidcClientSecret | b64enc | quote }}
{{- end }}
