apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tatara-operator.fullname" . }}
  labels:
    {{- include "tatara-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPERATOR_OIDC_CLIENT_SECRET: {{ .Values.operatorOidcClientSecret | quote }}
