//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	if in.ModelByKind != nil {
		in, out := &in.ModelByKind, &out.ModelByKind
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EffortByKind != nil {
		in, out := &in.EffortByKind, &out.EffortByKind
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Hooks != nil {
		in, out := &in.Hooks, &out.Hooks
		*out = new(LifecycleHooks)
		**out = **in
	}
	if in.ExtraEnvs != nil {
		in, out := &in.ExtraEnvs, &out.ExtraEnvs
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraEnvsFrom != nil {
		in, out := &in.ExtraEnvsFrom, &out.ExtraEnvsFrom
		*out = make([]v1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraVolumeMounts != nil {
		in, out := &in.ExtraVolumeMounts, &out.ExtraVolumeMounts
		*out = make([]v1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraVolumes != nil {
		in, out := &in.ExtraVolumes, &out.ExtraVolumes
		*out = make([]v1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraSidecarContainers != nil {
		in, out := &in.ExtraSidecarContainers, &out.ExtraSidecarContainers
		*out = make([]v1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraInitContainers != nil {
		in, out := &in.ExtraInitContainers, &out.ExtraInitContainers
		*out = make([]v1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoardSpec) DeepCopyInto(out *BoardSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoardSpec.
func (in *BoardSpec) DeepCopy() *BoardSpec {
	if in == nil {
		return nil
	}
	out := new(BoardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrainstormActivity) DeepCopyInto(out *BrainstormActivity) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrainstormActivity.
func (in *BrainstormActivity) DeepCopy() *BrainstormActivity {
	if in == nil {
		return nil
	}
	out := new(BrainstormActivity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrainstormOutcome) DeepCopyInto(out *BrainstormOutcome) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrainstormOutcome.
func (in *BrainstormOutcome) DeepCopy() *BrainstormOutcome {
	if in == nil {
		return nil
	}
	out := new(BrainstormOutcome)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CDScanActivity) DeepCopyInto(out *CDScanActivity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CDScanActivity.
func (in *CDScanActivity) DeepCopy() *CDScanActivity {
	if in == nil {
		return nil
	}
	out := new(CDScanActivity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeSummary) DeepCopyInto(out *ChangeSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeSummary.
func (in *ChangeSummary) DeepCopy() *ChangeSummary {
	if in == nil {
		return nil
	}
	out := new(ChangeSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronActivity) DeepCopyInto(out *CronActivity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronActivity.
func (in *CronActivity) DeepCopy() *CronActivity {
	if in == nil {
		return nil
	}
	out := new(CronActivity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentationSpec) DeepCopyInto(out *DocumentationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentationSpec.
func (in *DocumentationSpec) DeepCopy() *DocumentationSpec {
	if in == nil {
		return nil
	}
	out := new(DocumentationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaSpec) DeepCopyInto(out *GrafanaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaSpec.
func (in *GrafanaSpec) DeepCopy() *GrafanaSpec {
	if in == nil {
		return nil
	}
	out := new(GrafanaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaStatus) DeepCopyInto(out *GrafanaStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaStatus.
func (in *GrafanaStatus) DeepCopy() *GrafanaStatus {
	if in == nil {
		return nil
	}
	out := new(GrafanaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckActivity) DeepCopyInto(out *HealthCheckActivity) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckActivity.
func (in *HealthCheckActivity) DeepCopy() *HealthCheckActivity {
	if in == nil {
		return nil
	}
	out := new(HealthCheckActivity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImplementOutcome) DeepCopyInto(out *ImplementOutcome) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImplementOutcome.
func (in *ImplementOutcome) DeepCopy() *ImplementOutcome {
	if in == nil {
		return nil
	}
	out := new(ImplementOutcome)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssueOutcome) DeepCopyInto(out *IssueOutcome) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssueOutcome.
func (in *IssueOutcome) DeepCopy() *IssueOutcome {
	if in == nil {
		return nil
	}
	out := new(IssueOutcome)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleHooks) DeepCopyInto(out *LifecycleHooks) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleHooks.
func (in *LifecycleHooks) DeepCopy() *LifecycleHooks {
	if in == nil {
		return nil
	}
	out := new(LifecycleHooks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemorySpec) DeepCopyInto(out *MemorySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemorySpec.
func (in *MemorySpec) DeepCopy() *MemorySpec {
	if in == nil {
		return nil
	}
	out := new(MemorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryStatus) DeepCopyInto(out *MemoryStatus) {
	*out = *in
	if in.ReadySince != nil {
		in, out := &in.ReadySince, &out.ReadySince
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryStatus.
func (in *MemoryStatus) DeepCopy() *MemoryStatus {
	if in == nil {
		return nil
	}
	out := new(MemoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PROutcome) DeepCopyInto(out *PROutcome) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PROutcome.
func (in *PROutcome) DeepCopy() *PROutcome {
	if in == nil {
		return nil
	}
	out := new(PROutcome)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Project) DeepCopyInto(out *Project) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Project.
func (in *Project) DeepCopy() *Project {
	if in == nil {
		return nil
	}
	out := new(Project)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Project) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectList) DeepCopyInto(out *ProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Project, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectList.
func (in *ProjectList) DeepCopy() *ProjectList {
	if in == nil {
		return nil
	}
	out := new(ProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectSpec) DeepCopyInto(out *ProjectSpec) {
	*out = *in
	in.Agent.DeepCopyInto(&out.Agent)
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(MemorySpec)
		**out = **in
	}
	if in.Scm != nil {
		in, out := &in.Scm, &out.Scm
		*out = new(ScmSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Grafana != nil {
		in, out := &in.Grafana, &out.Grafana
		*out = new(GrafanaSpec)
		**out = **in
	}
	if in.Documentation != nil {
		in, out := &in.Documentation, &out.Documentation
		*out = new(DocumentationSpec)
		**out = **in
	}
	if in.Queue != nil {
		in, out := &in.Queue, &out.Queue
		*out = new(QueueSpec)
		**out = **in
	}
	if in.TokenBudget != nil {
		in, out := &in.TokenBudget, &out.TokenBudget
		*out = new(TokenBudgetSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectSpec.
func (in *ProjectSpec) DeepCopy() *ProjectSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectStatus) DeepCopyInto(out *ProjectStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(MemoryStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Grafana != nil {
		in, out := &in.Grafana, &out.Grafana
		*out = new(GrafanaStatus)
		**out = **in
	}
	if in.LastMRScan != nil {
		in, out := &in.LastMRScan, &out.LastMRScan
		*out = (*in).DeepCopy()
	}
	if in.LastIssueScan != nil {
		in, out := &in.LastIssueScan, &out.LastIssueScan
		*out = (*in).DeepCopy()
	}
	if in.LastBrainstorm != nil {
		in, out := &in.LastBrainstorm, &out.LastBrainstorm
		*out = (*in).DeepCopy()
	}
	if in.LastHealthCheck != nil {
		in, out := &in.LastHealthCheck, &out.LastHealthCheck
		*out = (*in).DeepCopy()
	}
	if in.LastDocumentation != nil {
		in, out := &in.LastDocumentation, &out.LastDocumentation
		*out = (*in).DeepCopy()
	}
	if in.LastCDScan != nil {
		in, out := &in.LastCDScan, &out.LastCDScan
		*out = (*in).DeepCopy()
	}
	if in.LastRefine != nil {
		in, out := &in.LastRefine, &out.LastRefine
		*out = (*in).DeepCopy()
	}
	if in.TokenBudget != nil {
		in, out := &in.TokenBudget, &out.TokenBudget
		*out = new(TokenBudgetStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ScanMarks != nil {
		in, out := &in.ScanMarks, &out.ScanMarks
		*out = make([]ScanMark, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectStatus.
func (in *ProjectStatus) DeepCopy() *ProjectStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProposedIssueSpec) DeepCopyInto(out *ProposedIssueSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProposedIssueSpec.
func (in *ProposedIssueSpec) DeepCopy() *ProposedIssueSpec {
	if in == nil {
		return nil
	}
	out := new(ProposedIssueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueSpec) DeepCopyInto(out *QueueSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueSpec.
func (in *QueueSpec) DeepCopy() *QueueSpec {
	if in == nil {
		return nil
	}
	out := new(QueueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueuedEvent) DeepCopyInto(out *QueuedEvent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueuedEvent.
func (in *QueuedEvent) DeepCopy() *QueuedEvent {
	if in == nil {
		return nil
	}
	out := new(QueuedEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueuedEvent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueuedEventList) DeepCopyInto(out *QueuedEventList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QueuedEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueuedEventList.
func (in *QueuedEventList) DeepCopy() *QueuedEventList {
	if in == nil {
		return nil
	}
	out := new(QueuedEventList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueuedEventList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueuedEventPayload) DeepCopyInto(out *QueuedEventPayload) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(TaskSource)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SystemicGroup != nil {
		in, out := &in.SystemicGroup, &out.SystemicGroup
		*out = new(SystemicGroup)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueuedEventPayload.
func (in *QueuedEventPayload) DeepCopy() *QueuedEventPayload {
	if in == nil {
		return nil
	}
	out := new(QueuedEventPayload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueuedEventSpec) DeepCopyInto(out *QueuedEventSpec) {
	*out = *in
	in.Payload.DeepCopyInto(&out.Payload)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueuedEventSpec.
func (in *QueuedEventSpec) DeepCopy() *QueuedEventSpec {
	if in == nil {
		return nil
	}
	out := new(QueuedEventSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueuedEventStatus) DeepCopyInto(out *QueuedEventStatus) {
	*out = *in
	if in.AdmittedAt != nil {
		in, out := &in.AdmittedAt, &out.AdmittedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueuedEventStatus.
func (in *QueuedEventStatus) DeepCopy() *QueuedEventStatus {
	if in == nil {
		return nil
	}
	out := new(QueuedEventStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RefineActivity) DeepCopyInto(out *RefineActivity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RefineActivity.
func (in *RefineActivity) DeepCopy() *RefineActivity {
	if in == nil {
		return nil
	}
	out := new(RefineActivity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Repository) DeepCopyInto(out *Repository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repository.
func (in *Repository) DeepCopy() *Repository {
	if in == nil {
		return nil
	}
	out := new(Repository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Repository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryList) DeepCopyInto(out *RepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Repository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryList.
func (in *RepositoryList) DeepCopy() *RepositoryList {
	if in == nil {
		return nil
	}
	out := new(RepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositorySpec) DeepCopyInto(out *RepositorySpec) {
	*out = *in
	if in.IngestEnabled != nil {
		in, out := &in.IngestEnabled, &out.IngestEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SemanticIngest != nil {
		in, out := &in.SemanticIngest, &out.SemanticIngest
		*out = new(bool)
		**out = **in
	}
	if in.ReporterLogins != nil {
		in, out := &in.ReporterLogins, &out.ReporterLogins
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.MaintainerLogins != nil {
		in, out := &in.MaintainerLogins, &out.MaintainerLogins
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositorySpec.
func (in *RepositorySpec) DeepCopy() *RepositorySpec {
	if in == nil {
		return nil
	}
	out := new(RepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryStatus) DeepCopyInto(out *RepositoryStatus) {
	*out = *in
	if in.LastIngestTime != nil {
		in, out := &in.LastIngestTime, &out.LastIngestTime
		*out = (*in).DeepCopy()
	}
	if in.LastScheduledReingest != nil {
		in, out := &in.LastScheduledReingest, &out.LastScheduledReingest
		*out = (*in).DeepCopy()
	}
	if in.LastIngestFailureTime != nil {
		in, out := &in.LastIngestFailureTime, &out.LastIngestFailureTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryStatus.
func (in *RepositoryStatus) DeepCopy() *RepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(RepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewVerdict) DeepCopyInto(out *ReviewVerdict) {
	*out = *in
	if in.Suggestions != nil {
		in, out := &in.Suggestions, &out.Suggestions
		*out = make([]Suggestion, len(*in))
		copy(*out, *in)
	}
	if in.Semver != nil {
		in, out := &in.Semver, &out.Semver
		*out = make([]SemverAssignment, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewVerdict.
func (in *ReviewVerdict) DeepCopy() *ReviewVerdict {
	if in == nil {
		return nil
	}
	out := new(ReviewVerdict)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanMark) DeepCopyInto(out *ScanMark) {
	*out = *in
	in.AccountedAt.DeepCopyInto(&out.AccountedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanMark.
func (in *ScanMark) DeepCopy() *ScanMark {
	if in == nil {
		return nil
	}
	out := new(ScanMark)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScmCron) DeepCopyInto(out *ScmCron) {
	*out = *in
	out.MRScan = in.MRScan
	out.IssueScan = in.IssueScan
	out.CDScan = in.CDScan
	in.Brainstorm.DeepCopyInto(&out.Brainstorm)
	in.HealthCheck.DeepCopyInto(&out.HealthCheck)
	out.Documentation = in.Documentation
	out.Refine = in.Refine
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScmCron.
func (in *ScmCron) DeepCopy() *ScmCron {
	if in == nil {
		return nil
	}
	out := new(ScmCron)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScmSpec) DeepCopyInto(out *ScmSpec) {
	*out = *in
	if in.MaintainerLogins != nil {
		in, out := &in.MaintainerLogins, &out.MaintainerLogins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReporterLogins != nil {
		in, out := &in.ReporterLogins, &out.ReporterLogins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Board != nil {
		in, out := &in.Board, &out.Board
		*out = new(BoardSpec)
		**out = **in
	}
	if in.Cron != nil {
		in, out := &in.Cron, &out.Cron
		*out = new(ScmCron)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScmSpec.
func (in *ScmSpec) DeepCopy() *ScmSpec {
	if in == nil {
		return nil
	}
	out := new(ScmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SemverAssignment) DeepCopyInto(out *SemverAssignment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SemverAssignment.
func (in *SemverAssignment) DeepCopy() *SemverAssignment {
	if in == nil {
		return nil
	}
	out := new(SemverAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Subtask) DeepCopyInto(out *Subtask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subtask.
func (in *Subtask) DeepCopy() *Subtask {
	if in == nil {
		return nil
	}
	out := new(Subtask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Subtask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubtaskList) DeepCopyInto(out *SubtaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Subtask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubtaskList.
func (in *SubtaskList) DeepCopy() *SubtaskList {
	if in == nil {
		return nil
	}
	out := new(SubtaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubtaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubtaskRef) DeepCopyInto(out *SubtaskRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubtaskRef.
func (in *SubtaskRef) DeepCopy() *SubtaskRef {
	if in == nil {
		return nil
	}
	out := new(SubtaskRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubtaskSpec) DeepCopyInto(out *SubtaskSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubtaskSpec.
func (in *SubtaskSpec) DeepCopy() *SubtaskSpec {
	if in == nil {
		return nil
	}
	out := new(SubtaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubtaskStatus) DeepCopyInto(out *SubtaskStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubtaskStatus.
func (in *SubtaskStatus) DeepCopy() *SubtaskStatus {
	if in == nil {
		return nil
	}
	out := new(SubtaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Suggestion) DeepCopyInto(out *Suggestion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Suggestion.
func (in *Suggestion) DeepCopy() *Suggestion {
	if in == nil {
		return nil
	}
	out := new(Suggestion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemicGroup) DeepCopyInto(out *SystemicGroup) {
	*out = *in
	if in.SameRepoSiblings != nil {
		in, out := &in.SameRepoSiblings, &out.SameRepoSiblings
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.CrossRepo != nil {
		in, out := &in.CrossRepo, &out.CrossRepo
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemicGroup.
func (in *SystemicGroup) DeepCopy() *SystemicGroup {
	if in == nil {
		return nil
	}
	out := new(SystemicGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Task) DeepCopyInto(out *Task) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Task.
func (in *Task) DeepCopy() *Task {
	if in == nil {
		return nil
	}
	out := new(Task)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Task) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskList) DeepCopyInto(out *TaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Task, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskList.
func (in *TaskList) DeepCopy() *TaskList {
	if in == nil {
		return nil
	}
	out := new(TaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskSource) DeepCopyInto(out *TaskSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskSource.
func (in *TaskSource) DeepCopy() *TaskSource {
	if in == nil {
		return nil
	}
	out := new(TaskSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskSpec) DeepCopyInto(out *TaskSpec) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(TaskSource)
		**out = **in
	}
	if in.ProposedIssue != nil {
		in, out := &in.ProposedIssue, &out.ProposedIssue
		*out = new(ProposedIssueSpec)
		**out = **in
	}
	if in.ReposInScope != nil {
		in, out := &in.ReposInScope, &out.ReposInScope
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SystemicGroup != nil {
		in, out := &in.SystemicGroup, &out.SystemicGroup
		*out = new(SystemicGroup)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskSpec.
func (in *TaskSpec) DeepCopy() *TaskSpec {
	if in == nil {
		return nil
	}
	out := new(TaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskStatus) DeepCopyInto(out *TaskStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DiscoveredIssues != nil {
		in, out := &in.DiscoveredIssues, &out.DiscoveredIssues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LinksSyncedURLs != nil {
		in, out := &in.LinksSyncedURLs, &out.LinksSyncedURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReviewVerdict != nil {
		in, out := &in.ReviewVerdict, &out.ReviewVerdict
		*out = new(ReviewVerdict)
		(*in).DeepCopyInto(*out)
	}
	if in.PROutcome != nil {
		in, out := &in.PROutcome, &out.PROutcome
		*out = new(PROutcome)
		**out = **in
	}
	if in.IssueOutcome != nil {
		in, out := &in.IssueOutcome, &out.IssueOutcome
		*out = new(IssueOutcome)
		**out = **in
	}
	if in.ImplementOutcome != nil {
		in, out := &in.ImplementOutcome, &out.ImplementOutcome
		*out = new(ImplementOutcome)
		**out = **in
	}
	if in.BrainstormOutcome != nil {
		in, out := &in.BrainstormOutcome, &out.BrainstormOutcome
		*out = new(BrainstormOutcome)
		**out = **in
	}
	if in.ChangeSummary != nil {
		in, out := &in.ChangeSummary, &out.ChangeSummary
		*out = new(ChangeSummary)
		**out = **in
	}
	if in.GateEnteredAt != nil {
		in, out := &in.GateEnteredAt, &out.GateEnteredAt
		*out = (*in).DeepCopy()
	}
	if in.LastActivityAt != nil {
		in, out := &in.LastActivityAt, &out.LastActivityAt
		*out = (*in).DeepCopy()
	}
	if in.DeadlineAt != nil {
		in, out := &in.DeadlineAt, &out.DeadlineAt
		*out = (*in).DeepCopy()
	}
	if in.PendingComments != nil {
		in, out := &in.PendingComments, &out.PendingComments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PendingInterjections != nil {
		in, out := &in.PendingInterjections, &out.PendingInterjections
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WorkItems != nil {
		in, out := &in.WorkItems, &out.WorkItems
		*out = make([]WorkItemRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeployDeadline != nil {
		in, out := &in.DeployDeadline, &out.DeployDeadline
		*out = (*in).DeepCopy()
	}
	if in.MergeWaitDeadline != nil {
		in, out := &in.MergeWaitDeadline, &out.MergeWaitDeadline
		*out = (*in).DeepCopy()
	}
	if in.ReviewResolveDeadline != nil {
		in, out := &in.ReviewResolveDeadline, &out.ReviewResolveDeadline
		*out = (*in).DeepCopy()
	}
	if in.Subtasks != nil {
		in, out := &in.Subtasks, &out.Subtasks
		*out = make([]SubtaskRef, len(*in))
		copy(*out, *in)
	}
	if in.IssueLinks != nil {
		in, out := &in.IssueLinks, &out.IssueLinks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PRLinks != nil {
		in, out := &in.PRLinks, &out.PRLinks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskStatus.
func (in *TaskStatus) DeepCopy() *TaskStatus {
	if in == nil {
		return nil
	}
	out := new(TaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenBudgetSpec) DeepCopyInto(out *TokenBudgetSpec) {
	*out = *in
	if in.SpawnCeilingByKind != nil {
		in, out := &in.SpawnCeilingByKind, &out.SpawnCeilingByKind
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PollIntervalSeconds != nil {
		in, out := &in.PollIntervalSeconds, &out.PollIntervalSeconds
		*out = new(int32)
		**out = **in
	}
	if in.MonitorOverage != nil {
		in, out := &in.MonitorOverage, &out.MonitorOverage
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenBudgetSpec.
func (in *TokenBudgetSpec) DeepCopy() *TokenBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(TokenBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenBudgetStatus) DeepCopyInto(out *TokenBudgetStatus) {
	*out = *in
	if in.WindowStart != nil {
		in, out := &in.WindowStart, &out.WindowStart
		*out = (*in).DeepCopy()
	}
	if in.FiveHourReset != nil {
		in, out := &in.FiveHourReset, &out.FiveHourReset
		*out = (*in).DeepCopy()
	}
	if in.WeeklyReset != nil {
		in, out := &in.WeeklyReset, &out.WeeklyReset
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenBudgetStatus.
func (in *TokenBudgetStatus) DeepCopy() *TokenBudgetStatus {
	if in == nil {
		return nil
	}
	out := new(TokenBudgetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkItemRef) DeepCopyInto(out *WorkItemRef) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastRefreshedAt != nil {
		in, out := &in.LastRefreshedAt, &out.LastRefreshedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkItemRef.
func (in *WorkItemRef) DeepCopy() *WorkItemRef {
	if in == nil {
		return nil
	}
	out := new(WorkItemRef)
	in.DeepCopyInto(out)
	return out
}
