//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	if in.ModelByKind != nil {
		in, out := &in.ModelByKind, &out.ModelByKind
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EffortByKind != nil {
		in, out := &in.EffortByKind, &out.EffortByKind
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Hooks != nil {
		in, out := &in.Hooks, &out.Hooks
		*out = new(LifecycleHooks)
		**out = **in
	}
	if in.ExtraEnvs != nil {
		in, out := &in.ExtraEnvs, &out.ExtraEnvs
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraEnvsFrom != nil {
		in, out := &in.ExtraEnvsFrom, &out.ExtraEnvsFrom
		*out = make([]corev1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraVolumeMounts != nil {
		in, out := &in.ExtraVolumeMounts, &out.ExtraVolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraVolumes != nil {
		in, out := &in.ExtraVolumes, &out.ExtraVolumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraSidecarContainers != nil {
		in, out := &in.ExtraSidecarContainers, &out.ExtraSidecarContainers
		*out = make([]corev1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraInitContainers != nil {
		in, out := &in.ExtraInitContainers, &out.ExtraInitContainers
		*out = make([]corev1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalEvidence) DeepCopyInto(out *ApprovalEvidence) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalEvidence.
func (in *ApprovalEvidence) DeepCopy() *ApprovalEvidence {
	if in == nil {
		return nil
	}
	out := new(ApprovalEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoardSpec) DeepCopyInto(out *BoardSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoardSpec.
func (in *BoardSpec) DeepCopy() *BoardSpec {
	if in == nil {
		return nil
	}
	out := new(BoardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrainstormActivity) DeepCopyInto(out *BrainstormActivity) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrainstormActivity.
func (in *BrainstormActivity) DeepCopy() *BrainstormActivity {
	if in == nil {
		return nil
	}
	out := new(BrainstormActivity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Comment) DeepCopyInto(out *Comment) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Comment.
func (in *Comment) DeepCopy() *Comment {
	if in == nil {
		return nil
	}
	out := new(Comment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronActivity) DeepCopyInto(out *CronActivity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronActivity.
func (in *CronActivity) DeepCopy() *CronActivity {
	if in == nil {
		return nil
	}
	out := new(CronActivity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentationSpec) DeepCopyInto(out *DocumentationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentationSpec.
func (in *DocumentationSpec) DeepCopy() *DocumentationSpec {
	if in == nil {
		return nil
	}
	out := new(DocumentationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaSpec) DeepCopyInto(out *GrafanaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaSpec.
func (in *GrafanaSpec) DeepCopy() *GrafanaSpec {
	if in == nil {
		return nil
	}
	out := new(GrafanaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaStatus) DeepCopyInto(out *GrafanaStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaStatus.
func (in *GrafanaStatus) DeepCopy() *GrafanaStatus {
	if in == nil {
		return nil
	}
	out := new(GrafanaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Issue) DeepCopyInto(out *Issue) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Issue.
func (in *Issue) DeepCopy() *Issue {
	if in == nil {
		return nil
	}
	out := new(Issue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Issue) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssueList) DeepCopyInto(out *IssueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Issue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssueList.
func (in *IssueList) DeepCopy() *IssueList {
	if in == nil {
		return nil
	}
	out := new(IssueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IssueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssueSpec) DeepCopyInto(out *IssueSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssueSpec.
func (in *IssueSpec) DeepCopy() *IssueSpec {
	if in == nil {
		return nil
	}
	out := new(IssueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssueStatus) DeepCopyInto(out *IssueStatus) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Comments != nil {
		in, out := &in.Comments, &out.Comments
		*out = make([]Comment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SpilledCommentsRefs != nil {
		in, out := &in.SpilledCommentsRefs, &out.SpilledCommentsRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Approval != nil {
		in, out := &in.Approval, &out.Approval
		*out = new(ApprovalEvidence)
		(*in).DeepCopyInto(*out)
	}
	if in.CommentsRetainedFrom != nil {
		in, out := &in.CommentsRetainedFrom, &out.CommentsRetainedFrom
		*out = (*in).DeepCopy()
	}
	if in.PendingComments != nil {
		in, out := &in.PendingComments, &out.PendingComments
		*out = make([]PendingComment, len(*in))
		copy(*out, *in)
	}
	if in.LastRefireCommentAt != nil {
		in, out := &in.LastRefireCommentAt, &out.LastRefireCommentAt
		*out = (*in).DeepCopy()
	}
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssueStatus.
func (in *IssueStatus) DeepCopy() *IssueStatus {
	if in == nil {
		return nil
	}
	out := new(IssueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleHooks) DeepCopyInto(out *LifecycleHooks) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleHooks.
func (in *LifecycleHooks) DeepCopy() *LifecycleHooks {
	if in == nil {
		return nil
	}
	out := new(LifecycleHooks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemorySpec) DeepCopyInto(out *MemorySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemorySpec.
func (in *MemorySpec) DeepCopy() *MemorySpec {
	if in == nil {
		return nil
	}
	out := new(MemorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryStatus) DeepCopyInto(out *MemoryStatus) {
	*out = *in
	if in.ReadySince != nil {
		in, out := &in.ReadySince, &out.ReadySince
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryStatus.
func (in *MemoryStatus) DeepCopy() *MemoryStatus {
	if in == nil {
		return nil
	}
	out := new(MemoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergeRequest) DeepCopyInto(out *MergeRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeRequest.
func (in *MergeRequest) DeepCopy() *MergeRequest {
	if in == nil {
		return nil
	}
	out := new(MergeRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MergeRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergeRequestList) DeepCopyInto(out *MergeRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MergeRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeRequestList.
func (in *MergeRequestList) DeepCopy() *MergeRequestList {
	if in == nil {
		return nil
	}
	out := new(MergeRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MergeRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergeRequestSpec) DeepCopyInto(out *MergeRequestSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeRequestSpec.
func (in *MergeRequestSpec) DeepCopy() *MergeRequestSpec {
	if in == nil {
		return nil
	}
	out := new(MergeRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergeRequestStatus) DeepCopyInto(out *MergeRequestStatus) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.Comments != nil {
		in, out := &in.Comments, &out.Comments
		*out = make([]Comment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SpilledCommentsRefs != nil {
		in, out := &in.SpilledCommentsRefs, &out.SpilledCommentsRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CommentsRetainedFrom != nil {
		in, out := &in.CommentsRetainedFrom, &out.CommentsRetainedFrom
		*out = (*in).DeepCopy()
	}
	if in.MergedAt != nil {
		in, out := &in.MergedAt, &out.MergedAt
		*out = (*in).DeepCopy()
	}
	if in.DeployedAt != nil {
		in, out := &in.DeployedAt, &out.DeployedAt
		*out = (*in).DeepCopy()
	}
	if in.PendingReview != nil {
		in, out := &in.PendingReview, &out.PendingReview
		*out = new(PendingReview)
		(*in).DeepCopyInto(*out)
	}
	if in.PendingComments != nil {
		in, out := &in.PendingComments, &out.PendingComments
		*out = make([]PendingComment, len(*in))
		copy(*out, *in)
	}
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeRequestStatus.
func (in *MergeRequestStatus) DeepCopy() *MergeRequestStatus {
	if in == nil {
		return nil
	}
	out := new(MergeRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Note) DeepCopyInto(out *Note) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Note.
func (in *Note) DeepCopy() *Note {
	if in == nil {
		return nil
	}
	out := new(Note)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingComment) DeepCopyInto(out *PendingComment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingComment.
func (in *PendingComment) DeepCopy() *PendingComment {
	if in == nil {
		return nil
	}
	out := new(PendingComment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PendingReview) DeepCopyInto(out *PendingReview) {
	*out = *in
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]ReviewFinding, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PendingReview.
func (in *PendingReview) DeepCopy() *PendingReview {
	if in == nil {
		return nil
	}
	out := new(PendingReview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Project) DeepCopyInto(out *Project) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Project.
func (in *Project) DeepCopy() *Project {
	if in == nil {
		return nil
	}
	out := new(Project)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Project) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectList) DeepCopyInto(out *ProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Project, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectList.
func (in *ProjectList) DeepCopy() *ProjectList {
	if in == nil {
		return nil
	}
	out := new(ProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectSpec) DeepCopyInto(out *ProjectSpec) {
	*out = *in
	in.Agent.DeepCopyInto(&out.Agent)
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(MemorySpec)
		**out = **in
	}
	if in.Scm != nil {
		in, out := &in.Scm, &out.Scm
		*out = new(ScmSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Grafana != nil {
		in, out := &in.Grafana, &out.Grafana
		*out = new(GrafanaSpec)
		**out = **in
	}
	if in.Documentation != nil {
		in, out := &in.Documentation, &out.Documentation
		*out = new(DocumentationSpec)
		**out = **in
	}
	if in.Queue != nil {
		in, out := &in.Queue, &out.Queue
		*out = new(QueueSpec)
		**out = **in
	}
	if in.TokenBudget != nil {
		in, out := &in.TokenBudget, &out.TokenBudget
		*out = new(TokenBudgetSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectSpec.
func (in *ProjectSpec) DeepCopy() *ProjectSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectStatus) DeepCopyInto(out *ProjectStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(MemoryStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Grafana != nil {
		in, out := &in.Grafana, &out.Grafana
		*out = new(GrafanaStatus)
		**out = **in
	}
	if in.LastIssueScan != nil {
		in, out := &in.LastIssueScan, &out.LastIssueScan
		*out = (*in).DeepCopy()
	}
	if in.LastSweepSuccess != nil {
		in, out := &in.LastSweepSuccess, &out.LastSweepSuccess
		*out = (*in).DeepCopy()
	}
	if in.LastBrainstorm != nil {
		in, out := &in.LastBrainstorm, &out.LastBrainstorm
		*out = (*in).DeepCopy()
	}
	if in.LastDocumentation != nil {
		in, out := &in.LastDocumentation, &out.LastDocumentation
		*out = (*in).DeepCopy()
	}
	if in.LastRefine != nil {
		in, out := &in.LastRefine, &out.LastRefine
		*out = (*in).DeepCopy()
	}
	if in.TokenBudget != nil {
		in, out := &in.TokenBudget, &out.TokenBudget
		*out = new(TokenBudgetStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ScanMarks != nil {
		in, out := &in.ScanMarks, &out.ScanMarks
		*out = make([]ScanMark, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectStatus.
func (in *ProjectStatus) DeepCopy() *ProjectStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueSpec) DeepCopyInto(out *QueueSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueSpec.
func (in *QueueSpec) DeepCopy() *QueueSpec {
	if in == nil {
		return nil
	}
	out := new(QueueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueuedEvent) DeepCopyInto(out *QueuedEvent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueuedEvent.
func (in *QueuedEvent) DeepCopy() *QueuedEvent {
	if in == nil {
		return nil
	}
	out := new(QueuedEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueuedEvent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueuedEventList) DeepCopyInto(out *QueuedEventList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QueuedEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueuedEventList.
func (in *QueuedEventList) DeepCopy() *QueuedEventList {
	if in == nil {
		return nil
	}
	out := new(QueuedEventList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueuedEventList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueuedEventPayload) DeepCopyInto(out *QueuedEventPayload) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(TaskSource)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NewTask != nil {
		in, out := &in.NewTask, &out.NewTask
		*out = new(QueuedTaskBlueprint)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueuedEventPayload.
func (in *QueuedEventPayload) DeepCopy() *QueuedEventPayload {
	if in == nil {
		return nil
	}
	out := new(QueuedEventPayload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueuedEventSpec) DeepCopyInto(out *QueuedEventSpec) {
	*out = *in
	in.Payload.DeepCopyInto(&out.Payload)
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueuedEventSpec.
func (in *QueuedEventSpec) DeepCopy() *QueuedEventSpec {
	if in == nil {
		return nil
	}
	out := new(QueuedEventSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueuedEventStatus) DeepCopyInto(out *QueuedEventStatus) {
	*out = *in
	if in.AdmittedAt != nil {
		in, out := &in.AdmittedAt, &out.AdmittedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueuedEventStatus.
func (in *QueuedEventStatus) DeepCopy() *QueuedEventStatus {
	if in == nil {
		return nil
	}
	out := new(QueuedEventStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueuedTaskBlueprint) DeepCopyInto(out *QueuedTaskBlueprint) {
	*out = *in
	if in.IssueKeys != nil {
		in, out := &in.IssueKeys, &out.IssueKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AlertRules != nil {
		in, out := &in.AlertRules, &out.AlertRules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueuedTaskBlueprint.
func (in *QueuedTaskBlueprint) DeepCopy() *QueuedTaskBlueprint {
	if in == nil {
		return nil
	}
	out := new(QueuedTaskBlueprint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RefineActivity) DeepCopyInto(out *RefineActivity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RefineActivity.
func (in *RefineActivity) DeepCopy() *RefineActivity {
	if in == nil {
		return nil
	}
	out := new(RefineActivity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Repository) DeepCopyInto(out *Repository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repository.
func (in *Repository) DeepCopy() *Repository {
	if in == nil {
		return nil
	}
	out := new(Repository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Repository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryList) DeepCopyInto(out *RepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Repository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryList.
func (in *RepositoryList) DeepCopy() *RepositoryList {
	if in == nil {
		return nil
	}
	out := new(RepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositorySpec) DeepCopyInto(out *RepositorySpec) {
	*out = *in
	if in.IngestEnabled != nil {
		in, out := &in.IngestEnabled, &out.IngestEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SemanticIngest != nil {
		in, out := &in.SemanticIngest, &out.SemanticIngest
		*out = new(bool)
		**out = **in
	}
	if in.ReporterLogins != nil {
		in, out := &in.ReporterLogins, &out.ReporterLogins
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.MaintainerLogins != nil {
		in, out := &in.MaintainerLogins, &out.MaintainerLogins
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositorySpec.
func (in *RepositorySpec) DeepCopy() *RepositorySpec {
	if in == nil {
		return nil
	}
	out := new(RepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryStatus) DeepCopyInto(out *RepositoryStatus) {
	*out = *in
	if in.LastIngestTime != nil {
		in, out := &in.LastIngestTime, &out.LastIngestTime
		*out = (*in).DeepCopy()
	}
	if in.LastScheduledReingest != nil {
		in, out := &in.LastScheduledReingest, &out.LastScheduledReingest
		*out = (*in).DeepCopy()
	}
	if in.LastIngestFailureTime != nil {
		in, out := &in.LastIngestFailureTime, &out.LastIngestFailureTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryStatus.
func (in *RepositoryStatus) DeepCopy() *RepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(RepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewFinding) DeepCopyInto(out *ReviewFinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewFinding.
func (in *ReviewFinding) DeepCopy() *ReviewFinding {
	if in == nil {
		return nil
	}
	out := new(ReviewFinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanMark) DeepCopyInto(out *ScanMark) {
	*out = *in
	in.AccountedAt.DeepCopyInto(&out.AccountedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanMark.
func (in *ScanMark) DeepCopy() *ScanMark {
	if in == nil {
		return nil
	}
	out := new(ScanMark)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScmCron) DeepCopyInto(out *ScmCron) {
	*out = *in
	out.IssueScan = in.IssueScan
	in.Brainstorm.DeepCopyInto(&out.Brainstorm)
	out.Documentation = in.Documentation
	out.Refine = in.Refine
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScmCron.
func (in *ScmCron) DeepCopy() *ScmCron {
	if in == nil {
		return nil
	}
	out := new(ScmCron)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScmSpec) DeepCopyInto(out *ScmSpec) {
	*out = *in
	if in.MaintainerLogins != nil {
		in, out := &in.MaintainerLogins, &out.MaintainerLogins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReporterLogins != nil {
		in, out := &in.ReporterLogins, &out.ReporterLogins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Board != nil {
		in, out := &in.Board, &out.Board
		*out = new(BoardSpec)
		**out = **in
	}
	if in.Cron != nil {
		in, out := &in.Cron, &out.Cron
		*out = new(ScmCron)
		(*in).DeepCopyInto(*out)
	}
	if in.ApprovalPhrases != nil {
		in, out := &in.ApprovalPhrases, &out.ApprovalPhrases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScmSpec.
func (in *ScmSpec) DeepCopy() *ScmSpec {
	if in == nil {
		return nil
	}
	out := new(ScmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Task) DeepCopyInto(out *Task) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Task.
func (in *Task) DeepCopy() *Task {
	if in == nil {
		return nil
	}
	out := new(Task)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Task) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskEvent) DeepCopyInto(out *TaskEvent) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskEvent.
func (in *TaskEvent) DeepCopy() *TaskEvent {
	if in == nil {
		return nil
	}
	out := new(TaskEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskList) DeepCopyInto(out *TaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Task, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskList.
func (in *TaskList) DeepCopy() *TaskList {
	if in == nil {
		return nil
	}
	out := new(TaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskSource) DeepCopyInto(out *TaskSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskSource.
func (in *TaskSource) DeepCopy() *TaskSource {
	if in == nil {
		return nil
	}
	out := new(TaskSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskSpec) DeepCopyInto(out *TaskSpec) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(TaskSource)
		**out = **in
	}
	if in.MergeOrder != nil {
		in, out := &in.MergeOrder, &out.MergeOrder
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AlertRules != nil {
		in, out := &in.AlertRules, &out.AlertRules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DocumentsTasks != nil {
		in, out := &in.DocumentsTasks, &out.DocumentsTasks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskSpec.
func (in *TaskSpec) DeepCopy() *TaskSpec {
	if in == nil {
		return nil
	}
	out := new(TaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskStats) DeepCopyInto(out *TaskStats) {
	*out = *in
	if in.AgentsRun != nil {
		in, out := &in.AgentsRun, &out.AgentsRun
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NotesSpilledRefs != nil {
		in, out := &in.NotesSpilledRefs, &out.NotesSpilledRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskStats.
func (in *TaskStats) DeepCopy() *TaskStats {
	if in == nil {
		return nil
	}
	out := new(TaskStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskStatus) DeepCopyInto(out *TaskStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StageEnteredAt != nil {
		in, out := &in.StageEnteredAt, &out.StageEnteredAt
		*out = (*in).DeepCopy()
	}
	if in.StageWorkStartedAt != nil {
		in, out := &in.StageWorkStartedAt, &out.StageWorkStartedAt
		*out = (*in).DeepCopy()
	}
	if in.PodStartedAt != nil {
		in, out := &in.PodStartedAt, &out.PodStartedAt
		*out = (*in).DeepCopy()
	}
	if in.Notes != nil {
		in, out := &in.Notes, &out.Notes
		*out = make([]Note, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PendingEvents != nil {
		in, out := &in.PendingEvents, &out.PendingEvents
		*out = make([]TaskEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Stats.DeepCopyInto(&out.Stats)
	if in.DeliveredAt != nil {
		in, out := &in.DeliveredAt, &out.DeliveredAt
		*out = (*in).DeepCopy()
	}
	if in.IssueRefs != nil {
		in, out := &in.IssueRefs, &out.IssueRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MRRefs != nil {
		in, out := &in.MRRefs, &out.MRRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FoldInFlight != nil {
		in, out := &in.FoldInFlight, &out.FoldInFlight
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskStatus.
func (in *TaskStatus) DeepCopy() *TaskStatus {
	if in == nil {
		return nil
	}
	out := new(TaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenBudgetSpec) DeepCopyInto(out *TokenBudgetSpec) {
	*out = *in
	if in.SpawnCeilingByKind != nil {
		in, out := &in.SpawnCeilingByKind, &out.SpawnCeilingByKind
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PollIntervalSeconds != nil {
		in, out := &in.PollIntervalSeconds, &out.PollIntervalSeconds
		*out = new(int32)
		**out = **in
	}
	if in.MonitorOverage != nil {
		in, out := &in.MonitorOverage, &out.MonitorOverage
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenBudgetSpec.
func (in *TokenBudgetSpec) DeepCopy() *TokenBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(TokenBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenBudgetStatus) DeepCopyInto(out *TokenBudgetStatus) {
	*out = *in
	if in.WindowStart != nil {
		in, out := &in.WindowStart, &out.WindowStart
		*out = (*in).DeepCopy()
	}
	if in.FiveHourReset != nil {
		in, out := &in.FiveHourReset, &out.FiveHourReset
		*out = (*in).DeepCopy()
	}
	if in.WeeklyReset != nil {
		in, out := &in.WeeklyReset, &out.WeeklyReset
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenBudgetStatus.
func (in *TokenBudgetStatus) DeepCopy() *TokenBudgetStatus {
	if in == nil {
		return nil
	}
	out := new(TokenBudgetStatus)
	in.DeepCopyInto(out)
	return out
}
